### ISSUE TITLE
Order Page is broken after installing this.

### ISSUE THREAD

**Issue by burhandodhy** [RBech/Quickpay_Payment#4] opened 2017-01-03 09:41 UTC
Hi,

I have installed this extension and now my order page is broken. http://prntscr.com/dqxjj3 . 

How i  can revert it back ?? 

Thanks

**Comment by RBech** [comment] 2017-01-03 12:37
You can of course remove the extension to completely revert it, but I would gladly help you troubleshoot why this is happening if you want? Usually it has to do with other extensions interfering

**Comment by RBech** [comment] 2017-01-05 09:02
@burhandodhy did you figure out the cause? :)

**Comment by RBech** [comment] 2017-01-09 20:45
@burhandodhy since you haven't returned I assume you figured out a solution, I'll close the issue for now but feel free to reopen it if you still need help

**Closed as completed by RBech** 2017-01-09 20:45 UTC
